/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uabc.proyectoalgoritmos;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author JesusOmar Leal
 */
public class InterfazMenu extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMenu
     */
    private ImageIcon imagen;
    private Icon icono;
    //Actualizar esta variable cada que se quiera ejecutar en un equipo nuevo
    private String rutaAssets = "C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoAlgoritmos\\src\\main\\java\\com\\uabc\\proyectoalgoritmos\\assets\\";
    private final Audio audio = new Audio(rutaAssets);
    
    private ArrayList<Integer> lista = new ArrayList<>();

    public InterfazMenu() {
        initComponents();

        //Agregar la ruta en assets
        this.setImagen(titulo, rutaAssets + "titulo2.png");
        this.setImagen(Background, rutaAssets + "background.jpg");
        audio.playAudio();
    }

    private void setImagen(JLabel lbl, String url) {

        this.imagen = new ImageIcon(url);

        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));

        lbl.setIcon(this.icono);

        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        generarNumerosB = new javax.swing.JButton();
        insertaNumerosB = new javax.swing.JButton();
        insertarUnNumeroB = new javax.swing.JButton();
        eliminarUnNumeroB = new javax.swing.JButton();
        recorrerPreOrdenB = new javax.swing.JButton();
        recorrerPostOrdenB = new javax.swing.JButton();
        recorrerInOrdenB = new javax.swing.JButton();
        recorrerPorNivelB = new javax.swing.JButton();
        encontrarNodosNivelB = new javax.swing.JButton();
        obtenerCodigoB = new javax.swing.JButton();
        Canva = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoAlgoritmos\\src\\main\\java\\com\\uabc\\proyectoalgoritmos\\assets\\titulo2.png")); // NOI18N
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 590, -1));

        generarNumerosB.setText("Generar Numeros");
        generarNumerosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarNumerosBActionPerformed(evt);
            }
        });
        jPanel1.add(generarNumerosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, -1));

        insertaNumerosB.setText("Inserta Numeros");
        insertaNumerosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaNumerosBActionPerformed(evt);
            }
        });
        jPanel1.add(insertaNumerosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        insertarUnNumeroB.setText("Insertar un Numero");
        insertarUnNumeroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarUnNumeroBActionPerformed(evt);
            }
        });
        jPanel1.add(insertarUnNumeroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, -1));

        eliminarUnNumeroB.setText("Eliminar un Numero");
        eliminarUnNumeroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUnNumeroBActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarUnNumeroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, -1));

        recorrerPreOrdenB.setText("Recorrer PreOrden");
        recorrerPreOrdenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorrerPreOrdenBActionPerformed(evt);
            }
        });
        jPanel1.add(recorrerPreOrdenB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, -1));

        recorrerPostOrdenB.setText("Recorrer PostOrden");
        recorrerPostOrdenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorrerPostOrdenBActionPerformed(evt);
            }
        });
        jPanel1.add(recorrerPostOrdenB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, -1));

        recorrerInOrdenB.setText("Recorrer InOrden");
        recorrerInOrdenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorrerInOrdenBActionPerformed(evt);
            }
        });
        jPanel1.add(recorrerInOrdenB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, -1));

        recorrerPorNivelB.setText("Recorrer Por Nivel");
        recorrerPorNivelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorrerPorNivelBActionPerformed(evt);
            }
        });
        jPanel1.add(recorrerPorNivelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, -1));

        encontrarNodosNivelB.setText("Encontrar Nodos Nivel");
        encontrarNodosNivelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encontrarNodosNivelBActionPerformed(evt);
            }
        });
        jPanel1.add(encontrarNodosNivelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, -1));

        obtenerCodigoB.setText("Obtener Codigo ");
        obtenerCodigoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerCodigoBActionPerformed(evt);
            }
        });
        jPanel1.add(obtenerCodigoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 160, -1));

        Canva.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CanvaLayout = new javax.swing.GroupLayout(Canva);
        Canva.setLayout(CanvaLayout);
        CanvaLayout.setHorizontalGroup(
            CanvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        CanvaLayout.setVerticalGroup(
            CanvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(Canva, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 470, 380));
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Icon icono(String ruta, int width, int height) {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
        return img;
    }


    private void generarNumerosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarNumerosBActionPerformed
        int valorMaximoAleatorios =Integer.parseInt( JOptionPane.showInputDialog(null, new JLabel("Ingresar el valor maximo: ")));
        int cantidadNumeros = Integer.parseInt(JOptionPane.showInputDialog(null, new JLabel("Ingresar la cantidad de numeros: ")));
        
        lista=Metodos.generarNumeros(valorMaximoAleatorios, cantidadNumeros);
        
        System.out.println(""+lista);
    }//GEN-LAST:event_generarNumerosBActionPerformed

    private void insertaNumerosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaNumerosBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaNumerosBActionPerformed

    private void insertarUnNumeroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarUnNumeroBActionPerformed
        int valorInsertado =Integer.parseInt( JOptionPane.showInputDialog(null, new JLabel("Ingresar el valor que deseas insertar: ")));
        
        System.out.println("Valor Insertado: "+valorInsertado);
    }//GEN-LAST:event_insertarUnNumeroBActionPerformed

    private void eliminarUnNumeroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUnNumeroBActionPerformed
       int valorEliminar =Integer.parseInt( JOptionPane.showInputDialog(null, new JLabel("Ingresar el valor que deseas eliminar: ")));
        
        System.out.println("Valor eliminado: "+valorEliminar);
    }//GEN-LAST:event_eliminarUnNumeroBActionPerformed

    private void recorrerPreOrdenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorrerPreOrdenBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recorrerPreOrdenBActionPerformed

    private void recorrerPostOrdenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorrerPostOrdenBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recorrerPostOrdenBActionPerformed

    private void recorrerInOrdenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorrerInOrdenBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recorrerInOrdenBActionPerformed

    private void recorrerPorNivelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorrerPorNivelBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recorrerPorNivelBActionPerformed

    private void encontrarNodosNivelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encontrarNodosNivelBActionPerformed
       int nivel =Integer.parseInt( JOptionPane.showInputDialog(null, new JLabel("Ingresar el nivel del arbol que desea ver : ")));
        
        System.out.println("nivel seleccionado: "+nivel);
    }//GEN-LAST:event_encontrarNodosNivelBActionPerformed

    private void obtenerCodigoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerCodigoBActionPerformed
        int numero =Integer.parseInt( JOptionPane.showInputDialog(null, new JLabel("Ingresar el numero que desea ver su codigo : ")));
        
        System.out.println("numero a buscar codigo: "+numero);
    }//GEN-LAST:event_obtenerCodigoBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Canva;
    private javax.swing.JButton eliminarUnNumeroB;
    private javax.swing.JButton encontrarNodosNivelB;
    private javax.swing.JButton generarNumerosB;
    private javax.swing.JButton insertaNumerosB;
    private javax.swing.JButton insertarUnNumeroB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton obtenerCodigoB;
    private javax.swing.JButton recorrerInOrdenB;
    private javax.swing.JButton recorrerPorNivelB;
    private javax.swing.JButton recorrerPostOrdenB;
    private javax.swing.JButton recorrerPreOrdenB;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
